# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: DearMob&Digiarty,Inc.DearMobiPhoneManager
PackageVersion: 6.0.0.0
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://www.5kplayer.com/download/dearmob-iphone-manager.exe
  InstallerSha256: 0D9171AC77643E96173E3C9D814CC3A9FDFB61A6D0373F075930C08CF9F7FC82
ManifestType: installer
ManifestVersion: 1.2.0

