# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.2.0.schema.json

PackageIdentifier: AdvancedMicroDevices,Inc.AMDRyzenMaster
PackageVersion: 2.10.0.2227
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.2.0

